### ISSUE TITLE
Do not let iPhone sleep while restoring

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1021]
This may be also considered for long syncs (if we can determine it) but generally speaking the iPhone should stay on while restoring. Otherwise the sync is stopped and it's very annoying to restore the wallet and be always on the phone tapping it to be awake.

**Comment by LukasKorba** [comment]
UIApplication.shared.isIdleTimerDisabled = true

**Comment by LukasKorba** [comment]
I think this is no longer valid for Zashi 1.0, let's make it a proposal for a product t decide if we even want/need it.

**Comment by LukasKorba** [comment]
Another approach could be to tell users to plug-in the device, that way the iPhone doesn't get sleep while restoring.

**Comment by true-jared** [comment]
I like that. Will track this for Product to evaluate and potentially prioritize post-Zashi 1.0. Thanks for the ideas @LukasKorba, please keep them coming! 🚀
