### ISSUE TITLE
KeysMissing when restored to a new iPhone

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1024]
This is actually very expected and technically not a bug because that is how iOS functions.

The DB is part of the app and goes to the backup while keys do not.
So any restore to a new iPhone will end up exactly in this state. The DB will be there but keys will be missing. I see only 3 options how to deal with this
- we can change the messaging into something like You probably restored to a different iPhone so you must delete Zashi and reinstall
- Zashi when detects this state will delete the DB and restore the wallet.
- Not sure if this one makes sense, could we ask to provide the seed and birthday and try to check if it matches the DB?

2nd option is something I struggle to recommend because automatic DB deletion sounds scary and I feel like this should be action of a user. So maybe we should add an option to the alert. Explaining what happened and add a button delete DB and restore my wallet rather than doing it without users attention.

![Image from iOS](https://github.com/Electric-Coin-Company/zashi-ios/assets/7198042/5c65cac9-26ae-4368-9f8a-ac94ba2bcf8f)

**Comment by daira** [comment]
> Not sure if this one makes sense, could we ask to provide the seed and birthday and try to check if it matches the DB?

Yes it should be possible to do that, and it's preferable because it recovers all information about historical transactions, not just the information that can be recovered from the chain. If the DB *doesn't* match then we can delete it.

**Comment by pacu** [comment]
oh, It looks I'm about to have this problem 🥶

**Comment by LukasKorba** [comment]
@true-jared there are 2 sides of this issues.

1. The keychain is async and sometimes the API fails to respond. Usually when the read request is happening early during the app start. We purposely wait a bit but you know the tech, depends on a device, performance, system overload etc. So I implemented a retry logic recently, when the keychain fails to respond, I'll wait a bit longer and try again. 3 times at most and then I call if a valid error (see point 2)
2. User really doesn't have a seed stored in the keychain but the DB is present. There is a scenario when this can actually happen. The DB is part of the app, on a disk. So when a user is backing up to he iCloud and later buys a new iPhone and restores from the iCloud backup, the Zashi is copied with the DB. We never backup keychain to the iCloud though so the seed is not copied to the new iPhone. And here's the state you're in. The seed + some other sensitive information are missing (keys) but the DB is present.

I see this task to be about several things
1. we need to improve the error message (up to you)
2. big question is IF we want AND even IF we CAN backup the DB. Th DB is in some way a sensitive piece of information and backing it up may be against our privacy/security/audit principles.
3. YES we want to keep the DB in the backup - then we need to be able to recover from this state, simple solution is to ask users to provide seed and validates it against the DB, this would mean a huge benefit for a user because they don't need to restore the wallet and as @nuttycom mentioned, they don't lose the history. 
4. NO, we don't want to backup the DB, then I need to mark the DB + many other files/folder to not go to the backup. A user will recover to a new iPhone and Zashi will be fully empty, starts at create a new wallet/restore from a backup. History is lost. I also think this is something a user can't know upfront, they simply don't know what trap await on them when they buy a new iPhone. 

So depending on the decision, goal of this task is either provide a UI for the seed validation or tell me to mark the files to not go to the backup.

**Comment by true-jared** [comment]
Decided with Josh that for 1.0 we will only improve the error messaging. We will discuss and plan out an improved solution for one of the later releases once we have clarity on the security impact of backing up the DB.

**Comment by true-jared** [comment]
@LukasKorba Im meeting Richard and Josh on Thursday and will get you the error screen design/copy we will use for this case for 1.0.

**Comment by pacu** [comment]
This comment should probably be a ZIP or a feature request somewhere, but here we go.

A few days ago I was pretty amazed by Signal's phone-to-phone recovery mechanism.

When you get a new device, you install Signal and your app is on a clean state. You can start over, but if you have the other device, you can pair them together to move the app state over to the new device, then the old one gets deleted. 

I think that as long as we have the "syncing problem" we should invest in this kind of workflows. I talk about this in a small tangent of the Wallet end-of-life Draft ZIP in the "accounting for user data" section of the ZIP. 

I know doing this in a "standardized way" would be the ideal, but I don't want perfect be the enemy of good.  Zashi and SDK powered apps have this problem where the use of Keychain and Trusted Execution Environments from the users' devices lead to a problem where backups are not done completely and users' information moves to the "new device" but the keys are not present.

I think this should be done more easily with an existing phone as Signal is doing.

**Comment by adjyrichard** [comment]
Please use this language:

Wallet setup failed. 

Zashi doesn’t recognize this device and wallet history. Please uninstall Zashi completely and reinstall it from scratch using your secret recovery phrase.

mock up in Figma.

**Comment by LukasKorba** [comment]
> Please use this language:
> 
> Wallet setup failed.
> 
> Zashi doesn’t recognize this device and wallet history. Please uninstall Zashi completely and reinstall it from scratch using your secret recovery phrase.
> 
> mock up in Figma and please let me know if you need anything else.

Will discuss it with Andrea but I think the message is not the one we need. If we go this way and temporarily stay in the state with no proper solution (don't backup the DB or implement validation flow) then we need to update the message for sure.

Our message should ideally explain what happened and what are the consequences for a user. With new knowledge and full understanding of false positive error ([read](https://github.com/Electric-Coin-Company/zashi-ios/issues/1068#issuecomment-1952159865)) we know know for sure that when this alert view is presented, a user surely migrated to a new device. Proposal for the message

`The data in this Zashi have been copied from a different device and because we never migrate recovery phrase for your safety, it's missing on this device. Ultim we implement a recovery phrase recovery the only option unfortunately for you is to delete Zashi and re-install it.` 

With this or reviewed/iterated message users should know and be aware of what happened. They very likely understand they migrated to a new device so they now understand why Zashi can't continue + understand the policy and security reasons which ideally gain us a credit and lower the annoyance on their side of upcoming delete and start over situation.

**Comment by daira** [comment]
This is Issue A in @earthrise's draft report:
> Issue A: Device-level backups are not restorable on a different device
> Severity: *Medium*
>
> zashi-ios stores its user’s seed phrase in the device’s keychain to protect it from unauthorized
access.
> For items stored in the keychain, the `kSecAttrAccessible` setting is set to `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`. According to Apple’s documentation:
> > This is recommended for items that need to be accessible only while the application is in the foreground. Items with this attribute do not migrate to a new device. Thus, after restoring from a backup of a different device, these items will not be present.
>
> On a technical level, this means that the backed-up seed phrase will be encrypted with a key that is only accessible to the current device. This creates a risk that, if a user loses or damages their phone, they will not be able to restore their seed phrase from any iTunes or iCloud backup of their phone.
> A user may reasonably expect that an iTunes or iCloud backup would contain all of their application data, including their Zcash seed phrase. If they mistakenly believe this, and do not separately back up their seed phrase, they will lose their funds.
> The risk of losing funds can be reduced by either:
> * Warning the user that their seed phrase will not be included in their device backup.
> * Using `kSecAttrAccessibleWhenUnlocked` instead. Restoring a backup on a different device will then include the seed phrase. This puts the seed phrase at a slightly higher risk of theft, since knowledge of the device passcode is sufficient to decrypt the backup.
> * Forcing the user to re-enter their seed phrase to prove that they have created a separate backup. (I recommend requiring the user to re-enter the entire seed phrase, not just some words, to ensure that there are no mistakes at all in the user’s backup.)
