### ISSUE TITLE
Zero available balance UX

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1030]

**Comment by LukasKorba** [comment]
A big topic we discussed many times. I personally think we should never present available balance 0 when it's very likely not a zero or we don't know the value yet. This topic goes even beyond this and one of other things that will greatly improve the UX is to show some spinner/progress in the UI. Even with Available balance 0, if the spinner is tight to this field, users would get some information. It's like

"ok, I see 0 which scares me a bit but on the other hand I see a spinner so it must be doing something and hopefully I'll see my balance again once this processing is done". 

And it will. 

There are also discussions if we get rid of the whole component, at least on an Account page. Another discussion was about renaming it to `spendable balance` or similar formats.

**Comment by true-jared** [comment]
@LukasKorba I tracked an issue for this on Friday where I referenced the conversation on Slack we had: https://github.com/Electric-Coin-Company/zashi-ios/issues/1043 Should we continue our conversation on this inside that issue and mark this one as a duplicate?

**Comment by true-jared** [comment]
Alternatively, I can copy the information I tracked into this one.

**Comment by LukasKorba** [comment]
> @LukasKorba I tracked an issue for this on Friday where I referenced the conversation on Slack we had: #1043 Should we continue our conversation on this inside that issue and mark this one as a duplicate?

Closing as duplicate then
