### ISSUE TITLE
Consolidate back button on the phrase display screen

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1037]
https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=1897-14731&mode=design&t=L69gPR22NMvtqLNn-0

**Comment by adjyrichard** [comment]
We decided to remove the button entirely and rely on upper left "Back" (needs implemented)
