### ISSUE TITLE
Detect orchard UA and notify users

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1039]
When orchard UA is scanned and users hope to send some funds to it, it fails. We discussed it and said we need to inform users this UA is not supported.

**Comment by str4d** [comment]
This issue was only necessary while Orchard was unimplemented. Once Orchard support is added to the SDK, this can be closed as "complete" immediately.

**Comment by LukasKorba** [comment]
Orchard is now supported so we no longer need to deal with this.
