### ISSUE TITLE
Resolve issues with available balance

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-ios#1043]
**Lukas:** 
Similarly like with AccountBalance? being an optional value, because there are cases when we simply don’t know.. spendableBalance being zero is a fallback, right? Seems like with WalletSummary it goes from rust through the FFI. The way I see it, the sync starts and spendableBalance is “invalidated” until new blocks are scanned and once done, it’s computed again and flips back to expected value. Isn’t true that during this period I call “invalidated” the spendableBalance should be also an optional instead of zero? If we don’t know the right value, it should either be last known or maybe better said, value that is true without new blocks affecting it, but very likely not zero. Zero is our approach how we fallback I believe. So in the end, the proper solution could be
```
public struct PoolBalance: Equatable {
    public let spendableValue: Zatoshi?
    public let changePendingConfirmation: Zatoshi
    public let valuePendingSpendability: Zatoshi
```
see
`public let spendableValue: Zatoshi?`

Instead of some value, most likely a fallback to zero. I think there’s no concept of optionals in rust or at least you can’t pass it through FFI. So it wound need to be some value we convert to nil afterwards I guess.
Note: this doesn’t solve the UX issue but it’s a better communication towards clients, presenting 0 because the value is always present vs. dealing with “we don’t know the value” makes the difference.

**Josh:** 
[For clarity, not related to 1.0]  It makes sense to me to be on the send page, but not on the home page. There is nothing I can do with it on that page, and really doesn't inform anything. If I'm opening it up to just check my balance, I don't need it. If I am opening it up to check a transaction, I don't need it. If I'm opening it up to receive a transaction, I don't need it. I really only need it if I'm intended to send ZEC. 

**Str4d:** 
There are two relevant states here:

- "I have no information about your balance" which implies no information about spendable balance. That is already represented as AccountBalance? so spendableBalance doesn't additionally need to be nil here.

- "I previously had information about your balance, but it might be out of date and unreliable". In this case, if we chose to set spendableBalance to nil, that would indeed convey we don't know the current spendable balance, but it would also lose information about what the last view of the spendable balance was. And spendableBalance isn't special here; in this state, all of the balance values are potentially incorrect.

To expand on the above, there are quite a few relevant states in which a wallet could reasonably show spendableBalance: 0 (there are actually a hypercube of states, but I can't draw that in a Slack thread, I need a whiteboard):

🔄 The wallet does not know about any funds, and is not fully scanned.
🛑 The wallet has no funds, and is fully scanned.
🛑 The wallet has been sent funds that have not been mined.
🔄 The wallet has been sent funds that might have been mined and sufficiently confirmed, but is not fully scanned.
⏸The wallet has been sent funds that have been mined but not sufficiently confirmed, and is fully scanned.
🛑  The wallet has created a transaction using the last spendable note(s) that it has not been mined.
🔄 The wallet has created a transaction using the last spendable note(s) that might have been mined and sufficiently confirmed, and is not fully scanned.
⏸The wallet has created a transaction using the last spendable note(s) that is mined but not sufficiently confirmed, and is fully scanned.

🛑 are states where the wallet has done everything it can and must wait; spendableBalance = 0 is accurate.
🔄 are states where the wallet can potentially change spendableBalance = 0 to a non-zero value by finishing scanning.
⏸ are states where spendableBalance = 0 is "only for security", and the funds could technically be spent (i.e. spendableBalance could be treated as non-zero) if the wallet is willing to risk a reorg / double-spend attack.

 <https://zcash.slack.com/archives/C02C1GZ0R6F/p1706971903502779?thread_ts=1706970299.685639&amp;cid=C02C1GZ0R6F|https://zcash.slack.com/archives/C02C1GZ0R6F/p1706971903502779?thread_ts=1706970299.685639&amp;cid=C02C1GZ0R6F>

[Slack Message](https://zcash.slack.com/archives/C02C1GZ0R6F/p1707362775326759?thread_ts=1707362775.326759&cid=C02C1GZ0R6F)

**Comment by LukasKorba** [comment]
Note: 
`"I have no information about your balance" which implies no information about spendable balance. That is already represented as AccountBalance? so spendableBalance doesn't additionally need to be nil here.`

is currently falling back to .zero on Zashi side, hence presenting 0. We should take advantage of optional (nil value) and change the UI accordingly. I won't create a separate ticket for it, just mentioning we should do this work as part of this one.

**Comment by true-jared** [comment]
We will plan a design session with Richard and Josh to clarify the requirements here. Josh confirmed that this is not a Zashi 1.0 requirement.

**Comment by true-jared** [comment]
I think this has been resolved some time ago with the loader icon. Closing this task.
