### ISSUE TITLE
Crashlytics acknowledge

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1051]
We somehow have integrated firebase which implies 2 things:

1. The questions is if we need to do some UI changes because of opt in/out choice of a user

2. if YES, we want to support firebase/crahslytics and we will implement UI, the Question is how to deliver GoogleService-info-plist. This file can't live in repo and must be attached to the project either manually or by CI. We used Bitrise to deliver this automatically but Bitrise is not used anymore. Github secrets would do the same job but it would mean to invest time into CI. The fastest solution is to attach the file to the project manually but it is also fragile because we can easily forgot to do it.

**Comment by true-jared** [comment]
Why did we stop using Bitrise - was it cost? It seems to me that we should definitely consider investing into CI if we do NOT have anything in place now and we are NOT planning to go back to Bitrise. Doing it manually presents a risk, I totally agree with you @LukasKorba.

**Comment by LukasKorba** [comment]
> Why did we stop using Bitrise - was it cost? It seems to me that we should definitely consider investing into CI if we do NOT have anything in place now and we are NOT planning to go back to Bitrise. Doing it manually presents a risk, I totally agree with you @LukasKorba.

The thing is there was pretty solid Bitrise setup but with lay-offs the account was replaced with a new one by Nick. He tried to setup some CI but never finished it and we yet again got a new account with Zooko. So during my time in Zcash, we have 3rd Bitrise account. Setting it up is from scratch would take me a lot of time so for Zashi 1.0 it's very unlikely to make it reality.

**Comment by daira** [comment]
Yes we need Crashlytics, and yes the user needs to be able to opt in or out. (Under GDPR, consent is the most appropriate legal basis here. Of the other possible grounds for collecting this information given at https://www.itgovernance.eu/blog/en/gdpr-when-do-you-need-to-seek-consent the only one that could be arguable is Legitimate Interest, and we clearly don't *need* the analytics data in order for the software to work.)

We will attach the file manually for the Zashi 1.0 beta and release, and then after the release we'll automate it.

**Comment by true-jared** [comment]
Do we already have a copy in mind or at least the information we need to include there @daira, so I can pass some instructions to Richard?

**Comment by LukasKorba** [comment]
> Do we already have a copy in mind or at least the information we need to include there @daira, so I can pass some instructions to Richard?

The question is how to solve this. In past we had a simple switch in settings and I think it was off by default. So people simply switched it on if they wanted. I think new plan is to show a prompt and ask users to opt in/out when they start the app for the first time, right? So @true-jared, we will need to know the whole solution, when, what, how, as always :)

**Comment by true-jared** [comment]
@daira @LukasKorba For 1.0 Josh has decided that we will only add wording to the Security Warning screen. @adjyrichard is working on adjusting the Figma design atm. When ready, I will run it by you @daira to check what you think.

**Comment by true-jared** [comment]
Link to the updated Security Warning screen: https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=3743-55693&mode=design&t=WiS2euBlSydG5JXU-4  @LukasKorba I should probably create a task for @HonzaR to update this on Android as well, right?

**Comment by LukasKorba** [comment]
> Link to the updated Security Warning screen: https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=3743-55693&mode=design&t=WiS2euBlSydG5JXU-4 @LukasKorba I should probably create a task for @HonzaR to update this on Android as well, right?

Yes, Honza needs to know
