### ISSUE TITLE
Improve successful restore message

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1053]
The restore of the wallet is pretty common operation many will face. Especially with inception of Zashi 1.0? When a user goes through the restore flow and successfully finishes it, this alert view is presented stating the success of restore operation.

### The Goal
Even though the message is simple yet "good enough" we miss an opportunity to actually explain what's going to happen from now on.

The restore of the wallet has a downside for a user no one will know until we teach them. During the restore the send of funds is not possible. We even implemented a whole set of UI enhancements to reflect restore of the wallet. (see the label at the top, progress on Account page + many more throughout the app). 

Yet I think it's not enough and we should modify this text to say something like `Restore of the wallet was successfully done, syncing may take a long time depending on the age of the wallet. NOTE: sending of funds is not possible during the restore.`

This should be enough for Zashi 1.0 but I think we should do much better some day in the future and present a screen that "celebrates" successful restore and explains the context there rather than in alert view. Generally speaking @true-jared we should try to use alert views as less as possible, for Zashi 1.0 it was the fastest solution.

![Simulator Screenshot - iPhone 15 Pro - 2024-02-14 at 08 34 33](https://github.com/Electric-Coin-Company/zashi-ios/assets/7198042/36396a93-3a64-47dc-8797-5633c7019c11)

**Comment by true-jared** [comment]
I think we can change the copy for 1.0 and follow your direction to improve it in one of the next releases, @LukasKorba. I would love to hear ideas how we could make a "celebratory" screen because the restore process is a little bit of a pain for the user, right? 

I checked on the copy with Chris, feel free to implement this: 

> Your wallet has been successfully restored! During the initial sync, your funds cannot be spent or sent. Depending on the age of your wallet, it may take a few hours to fully sync.
