### ISSUE TITLE
Handle unavailable AccountBalance

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1055]
The AccountBalance is an optional piece of data coming from SDK but Zashi fallbacks to .zero if it happens. `nil` value is a regular state we should reflect in the UI though so it must be handled and not ignored.

**Comment by true-jared** [comment]
Can we display a loader instead of 0 - is that an acceptable solution for 1.0? (to discuss with Josh and Richard)

**Comment by true-jared** [comment]
@LukasKorba Discussed this with Josh and Richard, and we can proceed with the loader!
