### ISSUE TITLE
Memo field behaviours for transparent address

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1060]
Send memo to the transparent address is not allowed and the memo field should grey-out. See the figma

https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=2030-16345&mode=design&t=IBEE7tnzlc2jvGQY-0

This worked in the past but newer iOS overlays the field with white box.

![Simulator Screenshot - iPhone 15 Pro - 2024-02-14 at 14 02 04](https://github.com/Electric-Coin-Company/zashi-ios/assets/7198042/ecf721a1-5789-49eb-af6d-3efbae695544)

Another question and a case we never solved on a product management level is what should happen when the memo holds some text and only after that a user uses some transparent address. Should we remove and leave the text inside the memo and all be greyed-out? @true-jared

**Comment by true-jared** [comment]
I have a quick sync with Richard and Josh tomorrow, let me check with them about this. I imagine that if we disable the box, we should remove the text because we will not allow the user to remove it themselves. What can we do with the overlay? Are you suggesting that we will need another design solution for the memo box? Like hiding it completely or something? @LukasKorba

**Comment by LukasKorba** [comment]
> I have a quick sync with Richard and Josh tomorrow, let me check with them about this. I imagine that if we disable the box, we should remove the text because we will not allow the user to remove it themselves. What can we do with the overlay? Are you suggesting that we will need another design solution for the memo box? Like hiding it completely or something? @LukasKorba

This is how it should look like, It worked until latest iOS changes so I'll need to fix it. 
NOTE: figma is not right, there is an arrow missing at the bottom like the field is a message. It's visible on my attached screen in the desc of this issue, ignore the white box inside. Ideally figma should be fixed so Honza won't implement box instead but keep the shape of a message, only make it grey filled.

<img width="293" alt="Screenshot 2024-02-15 at 8 54 16" src="https://github.com/Electric-Coin-Company/zashi-ios/assets/7198042/499a95a6-9022-49ff-951c-17b46320a101">

So essentially this issue is about 2 things:
1. fix the white box (on me)
2. what to do with the text inside when disabling it (on @true-jared )

**Comment by adjyrichard** [comment]
I think you just needed the box updated in Figma? It is done. If the issue is that we need another approach then please let me know.

**Comment by true-jared** [comment]
@LukasKorba The Figma design is fixed. I discussed this with Josh and Richard and we decided that we should NOT persist the memo text in case a user types in a transparent address. Let me know if there is anything else you need on this.
