### ISSUE TITLE
False positive keysMissing detection

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1068]
### Long story short
Josh & Pacu experienced this error state to be prompted even though the next start of Zashi resolved the issue. Unfortunately, there are no steps to reproduce.

### Sorry, the long story
I put a lot of thoughts into this and here is my assumption of what might be going on and what the implications are.

There are 2 scenarios:
1. The keys are truly missing, typically after iPhone restore
2. The keys are present but Zashi ends up in a conclusion the keys are missing (the next of this ticket explains why it might be the case)

First of all, this is a serious issue that has direct implication on #1024. @true-jared, I'm really worried about this because whenever this happens and it's a false positive we prompt them with message that is not true and even worse, we try to pull them into a flow of seed validation.

So the way I see it we must resolve this issue first before we can focus on a valid case when the keys are truly missing.

#### The seed rules Zashi
With seed, Zashi works and can work. Where is no seed, there is no working Zashi. This is very simple fact. Zashi tries to get the seed from the Keychain as soon as possible, ideally right after the start of Zashi.

#### The keychain
A few facts:
- The seed is stored in the keychain of an iPhone, nowhere else. The keychain API is probably the oldest API in iOS SDK, it doesn't support async await syntax whatsoever, it's very low level old way of coding. 
- The keychain is a system "storage", so it lives outside of Zashi. We can't control it, we can't demand a priority read or write, anything like it. So if we try to read the values from it, there are no guarantees it'll work at that very exact moment.

Especially the last point hit me and basically created a space for speculation(s). What if keychain is locked at the moment we want to read it? With async syntax, the system would wait and provide the value(s) asap. The API is not async one though so it either can provide the value or not. If not, it fails, simple as that.

The assumption is the keychain uses either a lock inside or operates with an operation queue so it should always return value. Yet there are cases when the retrival of the seed fails. We need to understand why.

#### The options we have
Since the API is something we can't fix or improve, we need to do some precautions. I implemented some retry simple [logic](https://github.com/Electric-Coin-Company/zashi-ios/pull/1000) that is apparently not enough and hasn't solved the issue. 

We could try to be more aggressive, increase the number of retry attempts, wait more time. This is something we will probably need to do anyway.

Another option is to implement a prompt with a spinner that says something like `syncing with the keychain...`, that will block users from accessing Zashi and periodically tries to read the values from the keychain until it gets the seed. The assumption here is that it must work and at some point it'll pass and unblocks users from accessing Zashi. We should try this as a prototype and internal solution so we can get some experience and answers.

My biggest worry now is that there might be some bug on iOS side and only new start of Zashi gets job done. This is also and still an option. Maybe Josh's and Pacu's run of Zashi simply failed because the API or system failed and fresh start was basically a restart of a computer (you know those cases when a restart is the only option). What I mean by this is maybe even a periodical try won't work until Zashi is restarted. We don't know that yet until we try to implement proposed prototype.

**Comment by LukasKorba** [comment]
I dug deep to understand the lowest levels of iOS, there are 56! possible error codes. My goal is to get the error code from the keychain and propagate it to the UI so we know which one exactly it is.

**Comment by LukasKorba** [comment]
I stress tested the keychain API, 1M reads/writes with no error, I think the API is pretty solid so I started to look somewhere else and actually there's a theory that would work so I'll focus on implementing this scenario to prove or deny it. 

The theory:
The keychain access flag is set to `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`. We have background task for bcg syncing every 3-4am. Even though our experience says the bcg sync works, it's at least confusing. The fresh start of the app during bcg syncing should fail to read see according to the flag. Because the device was locked.

Possible steps to reproduce the issue:
1. Start Zashi to make it work, go to the background to schedule bcg syncing for the next morning.
2. Kill the app from the background.
3. Lock the device, leave it on power and wifi.
4. Open the app next morning.

Expected behaviour:
1. The bcg syncing will awake Zashi at scheduled time.
2. Zashi will go through fresh start because it was killed.
3. Initialization pipeline will try to read seed from the keychain. `kSecAttrAccessibleWhenUnlockedThisDeviceOnly` flag should prevent from reading data.
4. Zashi fails and triggers alert view.
5. Zashi opened next morning starts from the background because it was awaken so it's not a fresh start.
6. Users will see alert view with keysMissing.

**Comment by pacu** [comment]
It is expected that background processes started with the background task APIs fail to get the keychain elements under the policies used by Zashi.


I think that it can be beneficial to actually split the logic between background start ups of the app and foreground. This will make Zashi start up without the keychain access that is not needed. An app started from the background can be assumed to have a db file that sync can work with.


Or make it simpler: not worrying about the spending capabilities until spending happens. 

The old ECC wallet gave up on background sync because of its clunkyness of the time. The buffer start screen worked fine for us.

Allowing Background sync changes that game and the start up cycle of the app will have to accommodate the fact that the seed should not be accessed from the background with the device locked 

I hope this context and walk through memory lane helps!

**Comment by LukasKorba** [comment]
@pacu I resolved everything on Saturday, a few PRs will be created in coming days.

**Comment by LukasKorba** [comment]
I finally found steps to reproduce the issue + I know the solution.

#### Why it’s happening?
Background syncing is the root cause but the conditions are very specific. Zashi was killed by the system from the background meanwhile, system was overloaded and running low on resources. Background task awakes the app and the SDK initalization starts, that process needs to get the seed from keychain but keychain is set to flag kSecAttrAccessibleWhenUnlockedThisDeviceOnly which doesn’t allow to read keychain when the device is locked.

And that is very likely true when you are sleeping, iPhone is connected to the wifi + power. So you wake up and find the alert view.

#### Solution(s)
I’m listing 2 and only 2 possible solutions just so you have full list but it’s clear that we will use only 1 of them

1. say bye to background syncing and stay as restrictive as possible when it comes to the keychain setup
2. change the flag of keychain, I propose kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly which means keychain can be accessed even when iPhone is locked (less secure btw) but must be unlocked after any restart of the device (all possible flags [here](https://developer.apple.com/documentation/security/keychain_services/keychain_items/item_attribute_keys_and_values?language=objc))

Fix is a one liner, we simply change the flag but I wanted you all to know the implications

#### What to expect after fix?
You will never see this error again as a false positive, you will see this error when it’s true, the seed is really not stored in the keychain, which is a task we still need to solve.

NOTE: you see now the status code in the alert view thanks to changes yesterday, here is the specification of this specific status code errSecInteractionNotAllowed       = -25308,  /* User interaction is not allowed. */

PS: none of the possible flags is actually best for this error, all leave the door open for a very specific and very rare edge case the error is thrown again, so I’ll also implement an internal flag that will prevent from throwing this error and throwing a different one with message like Something went wrong, please restart Zashi. I think this PS is post-1.0 task though
