### ISSUE TITLE
Total and available balances component

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#1087]
The total balance accompanied with available balance is presented at the top of Account, Home and Balances screens which make these 2 separate component and great candidate to compose it together and reduce redundant code.

**Comment by daira** [comment]
This comment from #1055 should also be resolved:
> It could be the case that there is actually zero shielded balance (and non-zero transparent balance) when fully scanned, which would cause the spinner to show incorrectly.
