### ISSUE TITLE
[Zashi-iOS audit] Issue D: Seed phrase entry could be intercepted by custom keyboards

### ISSUE THREAD

**Issue by daira** [Electric-Coin-Company/zashi-ios#1095]
From @defuse's draft report:
> Severity: *Medium*
>
> When importing a wallet from a seed phrase in Zashi, the user enters their seed phrase into a regular `TextEditor` field. If the user has a malicious custom keyboard installed, the keyboard could intercept the seed words and steal the user’s funds. Even if the custom keyboard is not malicious, it might inadvertently write seed phrase data somewhere less secure, such as into databases for predictive text or autocorrect.
> Instead, a `SecureTextEntry` should be used. This will prevent any third-party keyboard from accessing the seed phrase.

This seems relatively straightforward to fix: it is essentially just replacing `TextEditor` with `SecureTextEntry` [here](https://github.com/Electric-Coin-Company/zashi-ios/blob/2ba8f26d0a8e0bd8dbdd6f3e55dafdfe86855add/modules/Sources/Features/ImportWallet/ImportWalletView.swift#L48).

**Comment by LukasKorba** [comment]
> This seems relatively straightforward to fix: it is essentially just replacing `TextEditor` with `SecureTextEntry` [here](https://github.com/Electric-Coin-Company/zashi-ios/blob/2ba8f26d0a8e0bd8dbdd6f3e55dafdfe86855add/modules/Sources/Features/ImportWallet/ImportWalletView.swift#L48).

This is actually not a solution. `secureTextEntry` is not a replacement for TextEditor. It's not a View at all, it's a parameter of UIKit's UITextField. SwiftUI has something called `SecureField`, it's a View and does a typical password experience, when a user types, no characters are visible, instead there are dots (web browsers use usually *). 

The problem is we need Editor experience. TextEditor component is exactly what we need, the area where a user can write several words/sentences on a several lines. iOS 15 is not capable to provide `secureTextEntry` experience for Editors, there is not replacement for it.

**Comment by LukasKorba** [comment]
Proposed solution:

We already have a code in place that disables 3rd party keyboards.

```swift
func application(
        _ application: UIApplication,
        shouldAllowExtensionPointIdentifier extensionPointIdentifier: UIApplication.ExtensionPointIdentifier
    ) -> Bool {
        return extensionPointIdentifier != UIApplication.ExtensionPointIdentifier.keyboard
    }
```

@daira @true-jared is it ok for you that we don't let users to use any 3rd party keyboard in Zashi? It essentially forces them to switch the keyboard to a system one.

**Comment by daira** [comment]
> @daira @true-jared is it ok for you that we don't let users to use any 3rd party keyboard in Zashi? It essentially forces them to switch the keyboard to a system one.

Yes that is acceptable. It may slightly inconvenience users who want to use a third-party IME to enter text for memo fields, for example, but I think that's an acceptable trade-off to avoid this vulnerability. Any improvement would have to be post-Zashi 1.0.

To close this issue, it's sufficient to manually attempt to use a third-party keyboard (that can be easily distinguished from the built-in one) and check that it's disabled in Zashi when entering the seed phrase for wallet import.

**Comment by daira** [comment]
Another thing that would be good to do is to check that [dictation](https://support.apple.com/en-gb/guide/iphone/iph2c0651d2/ios) *does* still work. That verifies that we're not introducing an accessibility problem for users who find it difficult to type on the built-in keyboard. (If it doesn't work, open an issue, but this wouldn't be a blocker for 1.0.)

**Comment by pacu** [comment]
All iOS accessibility features (Dictation, voice over, etc) should work with the system keyboard

**Comment by daira** [comment]
@LukasKorba says:
> The system keyboard is already forced, no additional code needed. I tested 3rd party keyboards and Zashi automatically works in system keyboard only, not offering an option to switch to some other.
