### ISSUE TITLE
Unable to sync due to error

### ISSUE THREAD

**Issue by rex4539** [Electric-Coin-Company/zashi-ios#1164]
### Describe the issue
Zashi is unable to sync the blockchain because of an error.

#### If so, please list the steps to reproduce below:
1. Try to sync the wallet for the first time.

### Expected behaviour
Wallet is synced.

### Actual behaviour + errors
Sync is stuck at 0.9% with the following message "Zashi encountered an error while syncing, attempting to resolve..." but it never recovers.

- App Version: 1.0.3 (1)
- iOS Version: 17.4.1
- Device: iPhone 13

**Comment by rex4539** [comment]
Same with 1.0.4 (2)

**Comment by LukasKorba** [comment]
> Same with 1.0.4 (2)

Could you please try to switch the server and let us know? Thx

**Comment by rex4539** [comment]
Changing server worked.

The offending server was mainnet.lightwalletd.com
