### ISSUE TITLE
implement localization in Spanish

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-ios#1239]
- needs to be scoped out properly and we need to prepare the translation files

**Comment by nuttycom** [comment]
From @LukasKorba on #1386:

English texts attached.

The format is very simple, it's always 1 instance per line following this rule:
```
"" = "";
```
where the 1st field is a key and the 2nd field is the value itself, aka the text visible in the UI.
```
"key" = "text";
```

Leave the keys untouched at this point and only focus on the actual texts. As a result, I need this strings file in Spanish, there is no english anymore in the file. I will add this file next to the one with english texts and iOS will pick A or B depending on the settings of the iPhone. What must stay the same is the keys.

[Localizable.strings.zip](https://github.com/user-attachments/files/17490309/Localizable.strings.zip)

**Comment by LukasKorba** [comment]
Resolved in https://github.com/Electric-Coin-Company/zashi-ios/pull/1412
