### ISSUE TITLE
update Send screen UI and add support for the Address Book feature

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-ios#1342]
1. Send screen UI update: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=774-2025&t=D7bhjdX1e9GG8SL7-4

- update the input fields UI on the Send screen
- remove the "typical fee" text
- update the button UI
- add a new button for Address Book and update the QR code button

2. When a user fills in a transparent address, the Memo field should shrink and display the text "Transparent transactions can't have memos": https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1474-4228&t=D7bhjdX1e9GG8SL7-4

3. Address Book access: when a user taps on the Address Book icon, they should be routed to the Address Book screen where they can select a recipient by tapping on a contact: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1496-9283&t=D7bhjdX1e9GG8SL7-4

- in the header of the screen, we should display an additional copy "Select recipient" 

4. If a user pastes in a valid Zcash address that is not yet saved in their Address Book, we should display the Address Book icon with a + sign, and show them a tooltip nudging them to add the contact to their Address Book: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1980-2289&t=D7bhjdX1e9GG8SL7-4

- the Address Book icon should display a + sign in this case (until a user saves the address to their Address Book)
- the tooltip should be displayed for 3 seconds and then disappear on its own

5. Update the Confirmation screen UI based on the new design:

- shielded confirmation screen: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1759-47291&t=D7bhjdX1e9GG8SL7-4
- transparent confirmation screen: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1827-9450&t=D7bhjdX1e9GG8SL7-4

**Comment by LukasKorba** [comment]
Resolved in #1362
