### ISSUE TITLE
build new Integrations screen

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-ios#1344]
- final design: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1101-21087&t=fq3M7syJdTLIpY49-4

- access point in the app Settings: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=874-15376&t=fq3M7syJdTLIpY49-4

- during the Restore process, access to payment integrations has to be disabled because we cannot verify the wallet's balance: 
- final design: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1153-21113&t=fq3M7syJdTLIpY49-4

**Comment by LukasKorba** [comment]
Resolved in #1362
