### ISSUE TITLE
update Receive screen UI and build additional components

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-ios#1352]
- final Figma designs for the Receive screen UI: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=991-21967&t=D7bhjdX1e9GG8SL7-4

1. when a user taps on the Copy button, we should copy the corresponding address to their clipboard and display a success toast message

2. when a user taps on the QR code button, we should route them to the QR code screen:
- shielded QR code screen: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=962-3162&t=MDxlhe7GoQrvxaeE-4
- transparent QR code screen: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1018-22108&t=MDxlhe7GoQrvxaeE-4

3. When a user taps on a shielded address, we should display it in full. When a user taps on the expanded shielded address, we should collapse it: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=962-3215&t=MDxlhe7GoQrvxaeE-4

4. when a user taps on the Copy Address button, we should copy the corresponding address to their clipboard and display a success toast message 
- when a user long presses the address itself, we should also copy it into their clipboard and display a success toast message

5. when a user taps on the Share QR Code button, we should display the native sharing options displaying the app logo and sharing the QR code and a message copy: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1126-7776&t=MDxlhe7GoQrvxaeE-4

**Comment by LukasKorba** [comment]
Resolved in #1362
