### ISSUE TITLE
update Scan UI

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-ios#1359]
- update Scan UI based on the new design: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1746-3710&t=D7bhjdX1e9GG8SL7-4

- Error State - invalid Zcash Address: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1750-2934&t=D7bhjdX1e9GG8SL7-4

- Error State - Missing Permissions: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1750-3003&t=D7bhjdX1e9GG8SL7-4

- Device with no flash: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=1827-9382&t=D7bhjdX1e9GG8SL7-4

**Comment by LukasKorba** [comment]
Resolved in #1362
