### ISSUE TITLE
update buttons across the app and remove the grid pattern

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-ios#1373]
- update all the buttons across the whole app based on the new design system
- remove the grid pattern from the background of the screens
- update horizontal padding across the app to respect the new design system
- update places with sharp quadratic shapes to be rounded, so they go well with the new design: 

e.g.
- seed input box in the Create and Restore Wallet flow
- shielding box on the Balances screen: 
![IMG_6424](https://github.com/user-attachments/assets/53cd8bb3-4258-4ccf-9770-991d4aba7867)
- memo box in Transaction history:
![IMG_6423](https://github.com/user-attachments/assets/c7dc8252-2083-4fe0-9e42-241bd55f5ad8)

**Comment by LukasKorba** [comment]
Resolved in #1362
