### ISSUE TITLE
add device authentication method to app launch

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-ios#1378]
- implement using the device authentication method (Face ID, Touch ID or a passcode) on Zashi's app launch
- the authentication should happen on top of the HI splash screen
- if authentication fails and/or is cancelled, implement a fallback design: https://www.figma.com/design/ItxXKIvUZRpdabGhMAlmPs/PR-Designs-(2024)?node-id=3842-3704&t=gSoL6HmRMWrjLbTH-4

**Comment by LukasKorba** [comment]
Resolved in #1375
