### ISSUE TITLE
CrashReporterClient as isolated package

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#747]
The `CrashReporterClient` is a specific dependency that uses Firebase. We need to figure out how to import Firebase dependency into package and use FirebaseCore and FirebaseCraslytics out of it. Following the simple principles doesn't work with new package depenency like in other cases.

Google provides some [doc](https://firebase.google.com/docs/ios/installation-methods) but it is outdated, also referring to deprecated package definition with `name`. This also doesn't work. Plus there is need to define -ObjC flag, etc.

**Comment by daira** [comment]
This appears to have been fixed by #799.
