### ISSUE TITLE
Core BTS UI Improvements

### ISSUE THREAD

**Issue by nuttycom** [Electric-Coin-Company/zashi-ios#801]
The overall objective of this epic is to update the user interface elements of the IOS implementation of the Zashi cryptocurrency wallet conform to the design described by 

https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-branding-ADJY-MOCK?type=design&node-id=0%3A1&mode=design&t=9FayedV7L5uAZNyV-1

**Comment by timrmiller** [comment]
Could you verify that we are targeting phones only, not iPads?

**Comment by zookozcash** [comment]
Yes, phones only.

**Comment by LukasKorba** [comment]
Resolved in other tickets, irrelevant now.
