### ISSUE TITLE
Core BTS UI: About Screen

### ISSUE THREAD

**Issue by nuttycom** [Electric-Coin-Company/zashi-ios#807]
Update the "About" screen to conform to https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI-082123-V3?type=design&node-id=149%3A7969&mode=design&t=MuSYkgngwcFg2nNl-1

**Comment by LukasKorba** [comment]
| current version | expected version |
| --- | --- |
| ![Simulator Screenshot - iPhone 14 Pro - 2023-08-22 at 08 04 54](https://github.com/zcash/secant-ios-wallet/assets/7198042/a25fd531-9103-42f6-9e16-a12d227e6c6b) | <img width="344" alt="Screenshot 2023-08-22 at 8 05 50" src="https://github.com/zcash/secant-ios-wallet/assets/7198042/5aeda970-9d22-4705-a9f5-51723efcb00a"> |

- You can find this view in Features/ Settings/Views/About.swift
- all new texts must be added to the Features/Generated/Resources/Localizable.strings and referenced via SwiftGen's L10n
- Zashi logo & text can be downloaded at
[zashi_logo.zip](https://github.com/zcash/secant-ios-wallet/files/12405415/zashi_logo.zip)

**Comment by nuttycom** [comment]
@LukasKorba we should refer to the Figma document for the expected version, since that is the single source of truth for the designs and I don't want screenshots that might get posted in these issues to get stale.

**Comment by PraveenKumarVattipalli** [comment]
Do we need to Show Settings Icon in About Screen? as it is Navigating from Settings Screen. @nuttycom

**Comment by LukasKorba** [comment]
Resolved in other tickets, irrelevant now.
