### ISSUE TITLE
Core BTS UI: Settings Screen

### ISSUE THREAD

**Issue by nuttycom** [Electric-Coin-Company/zashi-ios#808]
https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI-082123-V3?type=design&node-id=149%3A7965&mode=design&t=MuSYkgngwcFg2nNl-1

**Comment by LukasKorba** [comment]
| current version | expected version |
| --- | --- |
| ![Simulator Screenshot - iPhone 14 Pro - 2023-08-22 at 08 14 37](https://github.com/zcash/secant-ios-wallet/assets/7198042/c952b6fd-5787-42c4-ae14-d1af9cc8b913) | <img width="346" alt="Screenshot 2023-08-22 at 8 15 08" src="https://github.com/zcash/secant-ios-wallet/assets/7198042/5fb6c53e-dc86-46d5-8f1c-cd37f14a54bf"> |

- You can find this view in Features/ Settings/SettingsView.swift
- all new texts must be added to the Features/Generated/Resources/Localizable.strings and referenced via SwiftGen's L10n
- hide the native back and implement custom one, use system's `arrow.left` for the the back arrow icon 
- customize the toggle to conform to the black/white design

**Comment by LukasKorba** [comment]
Resolved in other tickets, irrelevant now.
