### ISSUE TITLE
Persistency in onboarding flows

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#852]
There are two flows available in the onboarding screen.

1. create new wallet
2. restore wallet from seed

There are scenarios when a user started the flow but hasn't finished and next start of the app should let a user to continue the flow where it was interrupted. 

### Create New Wallet Flow
- persist the state of the warning screen, if a user for example acknowledges the warning but never taps the confirm button, next start should start at this screen with checked checkbox
- persist the state of a phrase backup screen, there we require a user to confirm the screen by tapping the "I got it" button. If the flow is for any reason interrupted before this button is tapped, next start of the app must start at the phrase screen
- consider the flow finished after the "I got it" is tapped

### Restore Wallet Flow
- persist the state when a user filled in a seed but hasn't finished the flow, either by tapping next or never finishing the birthday screen by tapping "restore", let a user to continue the flow and consider the flow to be finished after the "restore" is tapped

**Comment by nuttycom** [comment]
If a user has had the recovery phrase displayed to them, we probably need to ensure that the recovery phrase is not regenerated; if a user is shown the recovery phrase, they might have written it down, and if the wallet's seed then changes there's a risk that they could lose funds by failing to write down the new, different phrase.
