### ISSUE TITLE
Shielded transaction UI

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#937]
https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?node-id=2053%3A16416&mode=dev

- in the proposal we have a flag for shielding transactions but we need the information for Transaction History - that information should be in the V-transactions view (shielded notes received in a transaction and transparent notes getting spent)

**Comment by true-jared** [comment]
Design for all the scenarios you requested is here @LukasKorba: https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=2053-16416&mode=design&t=fu0piuvvDHEs4PmQ-4

<img width="735" alt="Screenshot 2024-05-01 at 13 41 58" src="https://github.com/Electric-Coin-Company/zashi-ios/assets/109794238/86c283b3-0d37-4547-b6ef-d3fa7134f28f">
