### ISSUE TITLE
Ensure is possible to see the seed under any circumstance

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#955]
If the SDK throws and error unexpectedly, users must be able to see the seed that is in the settings screen/display a recovery phrase

Ensure that none of the following cases/scenarios block a user from accessing the backup phrase screen
- wallet initialization failed
- sdk initialization failed
- sudden failure of a lightwalletd (service)

**Comment by nuttycom** [comment]
The UI flow should ideally be the same as normal; the main requirement here is that the UI is not disabled by failure of the SDK to initialize or failures in the network layer.
