### ISSUE TITLE
Scan UI

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#988]
The scan screen (overlaying the camera) needs to be enhanced to match the Zashi UI/UX. 

https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=3417-18019&mode=design&t=hQYH4zwFDImxBT4s-0

**Comment by adjyrichard** [comment]
Updated screens in Figma. Let me know if you want to discuss or I need to adjust.
