### ISSUE TITLE
Not enough free space UI

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#990]
We have this screen in Zashi but we miss the design for it. 

<img width="399" alt="Screenshot 2024-01-05 at 14 07 12" src="https://github.com/Electric-Coin-Company/zashi-ios/assets/7198042/1e3255d2-8a57-4ee0-b22e-b072aa5fbe0e">

**Comment by adjyrichard** [comment]
Added this to the Figma file.
<img width="391" alt="storage space" src="https://github.com/Electric-Coin-Company/zashi-ios/assets/149422369/15d30868-760b-44da-85c2-e172c197bd49">

**Comment by LukasKorba** [comment]
CLosing as duplicate #1029
