### ISSUE TITLE
Keys missing handling

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#997]
There's one particular state the Zashi can end up with and it's currently not handled other than a user gets stuck on a HI splash screen. The debug menu is accessible but hidden gesture is known only internally so this effectively means dead end for a user.

![Simulator Screenshot - iPhone 15 Pro - 2024-01-20 at 16 58 02](https://github.com/Electric-Coin-Company/zashi-ios/assets/7198042/3f242067-51f9-489b-ad42-806b9b9109b3)

`Keys missing` state means DB for the wallet is present and accessible but keychain and it's data are not. At this point we don't know why the keychain responds this way because in all cases we expect the wallet to be accessible, there was no external operation that would deleted the keychain data.

We might assume some cases or changes in the API like
- it takes time before the keychain is initialized and the API responses, we know this from past and that is why we purposely wait 0.01s before we even try to read the data. Maybe something changed and this time is no longer enough
- some other changes we don't know about

All in all if this happens for whatever reason, it's a dead end and terrible UX. 

### Goal
Ideally we get to know why the API responds this way so we can fix it. If this is not easily possible, other solution could be some retry logic, try to gradually read the data from keychain and don't stop after first failure.

So we can try to read the data in 0.01s like we do currently but failed state trigger another attempt in 0.05s. We can try up to 3 attempts for example and the last one in 0.1s. Then we should be fairly sure the data in the keychain are missing - the state when the app is truly not initialized.

**Comment by pacu** [comment]
I achieved to reproduce this by letting the app sleep a great deal of time and then calling it to foreground. Probably not the best reproduce steps because it take an important number of hours 🥶

**Comment by LukasKorba** [comment]
> I achieved to reproduce this by letting the app sleep a great deal of time and then calling it to foreground. Probably not the best reproduce steps because it take an important number of hours 🥶

This is great feedback anyway even without reproducing the issue. It only proves that your keys should be still in the keychain but read of it failed for whatever reason.
